### ISSUE TITLE
Missing string in LNG file

### ISSUE THREAD

**Issue by BestiaPL** [lazyhamster/IntChecker#39]
Choose: Validate files with params.

Configuration dialog uses label from lng file line 8 - there is ampersand, which is used in 'main menu'.
https://github.com/lazyhamster/IntChecker/blob/1f754e5c90b8a48e48f2196af87f763c47ec8fea/source/Text/IntCheckerEng.lng#L8

![image](https://user-images.githubusercontent.com/26287042/230600489-db4470fb-99e3-4c05-98cb-dfc5c903d5da.png)

**Comment by VictorVG** [comment]
Just in to latest public release Git 1f754e5c9 compiller don't use commit's:

[8da08b8] 2023-04-07 14:30:16 +0200 Andrzej Rudnik : Update history_pl.txt
[6ed3830] 2023-04-07 13:17:43 +0200 Andrzej Rudnik : Update readme_pl.txt.m4
[3759140] 2023-04-07 13:15:37 +0200 Andrzej Rudnik : Update IntCheckerPol.lng
[d162b5e] 2023-04-07 12:46:36 +0200 Andrzej Rudnik : Update history_pl.txt

Okay, now I’ll finish the repair of the equipment (the little things - the cable in the DVD -RW form ASUS nest dangled - the glass is a little larger than the connector and the result of a bunch of messages about the controller error, and at the same time I had to change the Arctic F8 bearing resource - the marking was made on February 11, 2002 - he honestly worked 7/24 for ten years and has the right to refuse :)) Then I will collect from the last sources since VC++ I have only available at that workstation.

**Comment by VictorVG** [comment]
Ready - build use MS VC++2019 v16.11.24:

[IntChecker2_Far3_x64_2.8.2.zip](https://github.com/lazyhamster/IntChecker/files/11180896/IntChecker2_Far3_x64_2.8.2.zip)
[IntChecker2_Far3_x86_2.8.2.zip](https://github.com/lazyhamster/IntChecker/files/11180899/IntChecker2_Far3_x86_2.8.2.zip)

include gitlog.txt - whats new after my latest build generated build script:

> [4cfbbe8] 2023-04-07 16:11:23 +0300 Vitaliy Didik : Merge pull request #38 from BestiaPL/master
> [8da08b8] 2023-04-07 14:30:16 +0200 Andrzej Rudnik : Update history_pl.txt
> [6ed3830] 2023-04-07 13:17:43 +0200 Andrzej Rudnik : Update readme_pl.txt.m4
> [3759140] 2023-04-07 13:15:37 +0200 Andrzej Rudnik : Update IntCheckerPol.lng
> [d162b5e] 2023-04-07 12:46:36 +0200 Andrzej Rudnik : Update history_pl.txt
> [1f754e5] 2023-04-07 13:14:38 +0300 Vitaliy Didik : Updated GH deployment token.
> [733ae1e] 2023-04-07 12:05:32 +0300 Vitaliy Didik : Updated RHash to 1.4.2.

**Comment by lazyhamster** [comment]
Added new separate line
ec75cd1c0179e3bcb4ccbdabd15e4df575ced5e4
